name: dart_dev
publish_to: none
homepage: https://dart.dev

environment:
  sdk: ^3.6.0

workspace:
  - tool/dart_site
  - examples
  - tool/get-dart

dependencies:
  cosmic_frontmatter: ^1.0.3
  jaspr: ^0.16.3
  jaspr_router: ^0.6.0
  liquid_engine: ^0.2.2
  markdown: ^7.2.2
  shelf: ^1.4.2
  shelf_proxy: ^1.0.4
  yaml: ^3.1.3

dev_dependencies:
  dart_site:
    path: tool/dart_site
  jaspr_builder: ^0.16.3

jaspr:
  mode: static
